[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.install]
cmds = ['cd backend && npm ci']

[phases.build]
cmds = ['cd backend && npm run build']

[start]
cmd = 'cd backend && npx prisma migrate deploy && node dist/server.js'
