[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['sh -c "cd backend && npm install"']

[phases.build]
cmds = ['sh -c "cd backend && npx prisma generate --schema=./prisma/schema.prisma && npx tsc"']

[start]
cmd = 'sh -c "cd backend && node dist/server.js"'


