[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['cd backend', 'npm install']

[phases.build]
cmds = ['cd backend', 'npx prisma generate', 'npx tsc']

[start]
cmd = 'sh -c "cd backend && node dist/server.js"'

